### ISSUE TITLE
Unable to load module

### ISSUE THREAD

**Issue by kamfaima** [jondwaite/vCDSitePair#1]
Hi, I'm unable to load the module and see the functions exported. I can confirm that the `Invoke-vCloud` module exports correctly as I can see it in the output of Get-Module as per below:

```
PS C:\Users\kamfai.ma> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      Invoke-vCloud                       Invoke-vCloud
```
I also tried changing `FunctionsToExport = @()` to `FunctionsToExport = '*'` in the manifest but still couldn't see the exported functions.

**Comment by jondwaite** [comment]
I've recently updated the module to remove any external dependencies and provide functionality to remove existing site links as well as create new site pairings. Hopefully this resolves your issue.
